### ISSUE TITLE
NameError: name 'BASE_ROOT' is not defined

### ISSUE THREAD

**Issue by shackdown** [oc-courses/deployez_une_application_django#2]
Bonjour,

Je tente de suivre votre formation sur OC mais j'ai quelques soucis avec la commande 

`./manage.py collectstatic`

J'obtiens les traces suivantes : 

`(env) cyril@vps723048:~/disquaire$ ./manage.py collectstatic
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cyril/disquaire/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/cyril/disquaire/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/home/cyril/disquaire/env/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/cyril/disquaire/env/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/cyril/disquaire/env/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/cyril/disquaire/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cyril/disquaire/disquaire_project/settings.py", line 144, in <module>
    STATIC_ROOT = os.path.join(BASE_ROOT, 'staticfiles')

NameError: name 'BASE_ROOT' is not defined
`

Est-ce que j'ai loupé une étape svp ? j'ai relu plusieurs fois le cours sans succés.

merci

**Comment by shackdown** [comment]
Bonjour,

Cela va peut-être aider les suivants.

Il faut définir le BASE_ROOT dans le settings, chose que j'ai fait en dupliquant la ligne BASE_DIR.
`
BASE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
`
